### PR TITLE
CHORE: Split packages

### PR DESCRIPTION
**Pull request by RafaDev95**
# Work in progress.

### Current ideia about the packages responsability: 
link: https://app.eraser.io/workspace/COEYRBHNlBuqIhcmKscz?origin=share

diagram-export-23-10-2024-09_30_23

### CODE REVIEW

**Comment by luisburigo** [comment]
Great work! Just need a few adjustments.

**Comment by RafaDev95** [comment]
> Great work! We just need a few adjustments to work better with monorepos:
> 
> We can implement the following structure
> 
> ```
> 📂 bako-safe-ui   // Root
> ┣ 📂 packages     // All libraries, utils, etc.. 
> ┃ ┗ 📦 bako-ui
> ┃ ┗ 📦 bako-services  
> ┣ 📂 apps         // All ui applications
> ┃ ┗ 📦 bako-app
> ┃ ┗ 📦 bako-dapp
> ┃ 
> ┃ ... some other folders/files
> ```
> 
> For this, you need to create a `pnpm-workspace.yaml` file in the `root` to define the workspaces
> 
> ```yaml
> packages:
>   - 'packages/*'
>   - 'apps/*'
> ```
> 
> In the dependencies that require a package from a workspace, they can be imported directly in the `package.json`
> 
> ```json
> "dependencies": {
>   "@bako-safe/ui": "workspace:*",
>   "@bako-safe/services": "workspace:*",
> },
> ```
> 
> @RafaDev95

Thanks for the help :) !

The workspace strategy is working great. The Bako-app is already using those packages.

**Comment by RafaDev95** [comment]
### List of possibles features/functions that could be moved into `Bako-Wallet` package

- `useWalletSignIn.tsx`: Interaction with fuel to handle the first response to authenticate user (depends on useAuth hook);
- The `fuel` folder from `core/hooks/fuel`: useConnect, useCurrentAccount, useIsConnected, useListConnectors, useNetwork, useProvider, useWallet
- `createVault.ts`: call SDK to create a vault`;
- `instantiateVault.ts`: call SDK to instantiate a vault
- `sendTransaction,ts`: call SDK to send a tx

**Comment by guimroque** [comment]
- receber logout como parametro do tipo useQuery
- receber o api como uma instancia do axios
- criar uma classe do tipo singleton

**Comment by guimroque** [comment]
- move cookies file to package `wallet`
- move api file to package `wallet` and change to singleton class

**Comment by guimroque** [comment]
- move the webauthn resources to wallet

**Comment by guimroque** [comment]
- remove of app, all locals when dapp pages os components are used

**Comment by guimroque** [comment]
- on app, remove all things about workspaces and dapp

**Comment by guimroque** [comment]
- change packages and apps names:

bako-app -> app
bako-dapp -> connector

bako-services -> services
bako-ui -> design-system
bako-wallet -> wallet

**Comment by RafaDev95** [comment]
> On axios file config of apps:
> 
> * Receive logout as a parameter of type useQuery
> * Receive the api as an instance of axios

Done: e0b1e3349ce1af8421f76e6af914fc2c578bc0fd

**Comment by RafaDev95** [comment]
> * move cookies file to package `wallet`
> * move api file to package `wallet` and change to singleton class

Done: e0b1e3349ce1af8421f76e6af914fc2c578bc0fd

**Comment by guimroque** [comment]
- the addAssetDialogComponent `apps/bako-app/src/components/addAssetsDialog/index.tsx` are used just on vault module, move to `apps/bako-app/src/components/addAssetsDialog/index.tsx`

**Comment by guimroque** [comment]
- `AddressWithCopyBtn` is a core component, move to `apps/bako-app/src/modules/core/components`

**Comment by guimroque** [comment]
- move `BakoLoading` to `packages/bako-ui`

**Comment by guimroque** [comment]
- move `CommingSoonDialog` to `packages/bako-ui`

**Comment by guimroque** [comment]
- move component `CopyAddressButton` to `packages/bako-ui`

**Comment by guimroque** [comment]
- move `WelcomeDialog` to `apps/bako-app/src/modules/core/components` and move the component `DepositDialog` to this component folder, keep: card.tsx, index.tsx and depositDialog.tsx

**Comment by guimroque** [comment]
- move `UserBox` on `apps/bako-app/src/layouts/dashboard/header.tsx` to `apps/bako-app/src/modules/core/components`

**Comment by guimroque** [comment]
- change wallet and ui packages exports of build, and update imports on project, check this pr to reference 536247e4af8c6be20036a47d9d4959ba8c2e8b55

**Comment by RafaDev95** [comment]
> * the addAssetDialogComponent `apps/bako-app/src/components/addAssetsDialog/index.tsx` are used just on vault module, move to `apps/bako-app/src/components/addAssetsDialog/index.tsx`

In this commit i've moved all components: 9754803e95f39270b87e106e77137cb8bec643ec

**Comment by guimroque** [comment]
- re-implement the axios instance created in service on app
- split on service fns related of webauthn and browser -> browser api (use wallet), request to api (use service), and wallet imports service

**Pull request closed without merging**
